# Generated by Django 5.2.17 on 2026-09-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_title',
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.job'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_application'),
        ),
    ]
